server:
  port: 9090
  servlet:
    context-path: /bits/
spring:
  application:
    name: bits_Banco
    version: develop
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
