server:
  port: 9090
  servlet:
    context-path: /bits/
spring:
  application:
    name: bits_Banco
    version: develop
  datasource:
    url: jdbc:mariadb://192.168.1.56:33066/dbBitsBancario
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    jpa:
      hibernate:
        dll: create-drop

